apiVersion: v1
kind: Service
metadata:
  name: knote-java
spec:
  selector:
    app: knote-java
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote-java
  template:
    metadata:
      labels:
        app: knote-java
    spec:
      containers:
        - name: app
          image: amruthamishra9099/knote-java:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
